### ISSUE TITLE
App crashes initially *Logcat saying " java.lang.ArithmeticException: divide by zero" *

### ISSUE THREAD

**Issue by Tracklous** [ElekenAgency/ReactNativeWheelPicker#64]
Whenever I launch the demo app with wheelpicker or any picker component, the app gets crashed. Logcat showing  **java.lang.ArithmeticException: divide by zero** .

*Any workaround available then please let me know via comment :)*

**Comment by chilidoggca** [comment]
Passing literal array fixed the issue for me. I was passing [...Array(32).keys()].slice(1) as data which crashed the app. Not sure why this worked in the older project.

**Comment by dschmaryl** [comment]
Are you sure that is what fixed it? I can use `data={[...Array(32).keys()].slice(1)}` without the "divide by zero" error (although it doesn't produce any data which i think is because of the use of the keys method). I am also using 1.1.14. The only way I am able to reproduce the "divide by zero" error is with either `style={{}}` or if you only pass styles that wheelpicker ignores such as `style={{fontSize: 10}}` Seems as if you must include at least one of either 'height' or 'width'.

**Comment by chilidoggca** [comment]
Hi dschmaryl, I was able to pass array keys as data in an older project using version 1.1.2 and react native 0.55. It is working smoothly. It has been implemented for months with no problems.

My newer project using 1.1.4 and react native 0.54 produced this exception. I have always passed style props including height and width. The only thing that fixed this exception was passing literal arrays as data. The code is essentially the same. It could be the RN version since reversing this library to 1.1.2 did not fix the exception.

**Comment by AleksandrChernyavenko** [comment]
For me crash happens when I send `data` = `[]`.
As workaround you can avoid sending empty array.

See [what cause this](https://github.com/KalonTech/ReactNativeWheelPicker/blob/58d7861f4e1ef22d4f386ec7b2972413b1b5213d/android/src/main/java/com/wheelpicker/LoopView.java#L195)

**Comment by akshgods** [comment]
hi @AleksandrChernyavenko , @chilidoggca 

my app running perfectly in ios
while it crashing in android. same code same array in both no code change.
i'm using wheel picker

error logs:

12-06 20:37:00.730  6920  6962 I ReactNativeJS: componentDidUpdate
12-06 20:37:00.764  6920  6920 W System.err: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
12-06 20:37:00.765  6920  6920 W System.err: 	at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:101)
12-06 20:37:00.765  6920  6920 W System.err: 	at com.wheelpicker.WheelPickerManager.setData(WheelPickerManager.java:53)
12-06 20:37:00.765  6920  6920 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
12-06 20:37:00.765  6920  6920 W System.err: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
12-06 20:37:00.765  6920  6920 W System.err: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:131)
12-06 20:37:00.765  6920  6920 W System.err: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
12-06 20:37:00.765  6920  6920 W System.err: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:46)
12-06 20:37:00.765  6920  6920 W System.err: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:268)
12-06 20:37:00.766  6920  6920 W System.err: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:198)
12-06 20:37:00.766  6920  6920 W System.err: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1036)
12-06 20:37:00.766  6920  6920 W System.err: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1007)
12-06 20:37:00.766  6920  6920 W System.err: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
12-06 20:37:00.766  6920  6920 W System.err: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172)
12-06 20:37:00.766  6920  6920 W System.err: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
12-06 20:37:00.766  6920  6920 W System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
12-06 20:37:00.766  6920  6920 W System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
12-06 20:37:00.766  6920  6920 W System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:721)
12-06 20:37:00.766  6920  6920 W System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
12-06 20:37:00.766  6920  6920 W System.err: 	at android.os.Handler.handleCallback(Handler.java:883)
12-06 20:37:00.766  6920  6920 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-06 20:37:00.766  6920  6920 W System.err: 	at android.os.Looper.loop(Looper.java:214)
12-06 20:37:00.766  6920  6920 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-06 20:37:00.766  6920  6920 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
12-06 20:37:00.766  6920  6920 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-06 20:37:00.766  6920  6920 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
12-06 20:37:00.811  6920  6943 D EGL_emulation: eglMakeCurrent: 0xdbb1ea80: ver 3 0 (tinfo 0xe7e88e50)
12-06 20:37:00.820  6920  6920 D AndroidRuntime: Shutting down VM
12-06 20:37:00.824  6920  6920 E AndroidRuntime: FATAL EXCEPTION: main
12-06 20:37:00.824  6920  6920 E AndroidRuntime: Process: com.genba.dev, PID: 6920
12-06 20:37:00.824  6920  6920 E AndroidRuntime: java.lang.ArithmeticException: divide by zero
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at com.wheelpicker.LoopView.onDraw(LoopView.java:195)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.draw(View.java:21421)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.buildDrawingCacheImpl(View.java:20695)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.buildDrawingCache(View.java:20555)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.draw(View.java:21145)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:684)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.draw(View.java:21424)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20298)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.draw(View.java:21153)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:684)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20289)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.draw(View.java:21153)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:684)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20289)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.draw(View.java:21153)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:684)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20289)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20258)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20258)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20258)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20258)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3610)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3418)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2755)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:725)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-06 20:37:00.824  6920  6920 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
12-06 20:37:00.830  2022  2538 W ActivityTaskManager:   Force finishing activity com.genba.dev/.MainActivity
12-06 20:37:00.833  2022  2538 W InputReader: Device has associated, but no associated display id.
12-06 20:37:00.833  2022  2538 I chatty  : uid=1000(system) Binder:2022_9 identical 8 lines
12-06 20:37:00.833  2022  2538 W InputReader: Device has associated, but no associated display id.
12-06 20:37:00.836  6920  6920 I Process : Sending signal. PID: 6920 SIG: 9
12-06 20:37:00.838  2022  7067 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
12-06 20:37:00.848  2022  2055 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
12-06 20:37:00.848  2022  2055 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
12-06 20:37:00.937  2022  2138 W InputDispatcher: channel 'ccbead6 com.genba.dev/com.genba.dev.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-06 20:37:00.937  2022  2138 E InputDispatcher: channel 'ccbead6 com.genba.dev/com.genba.dev.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-06 20:37:00.943  2022  2138 W InputDispatcher: channel '90d554f com.genba.dev/com.genba.dev.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-06 20:37:00.944  2022  2138 E InputDispatcher: channel '90d554f com.genba.dev/com.genba.dev.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-06 20:37:00.945  2022  3891 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=27, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10133] ], android.os.BinderProxy@e2a35e0)
12-06 20:37:00.958  2022  2164 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=27, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10133] ] (release request)
12-06 20:37:00.959  2022  2040 I ActivityManager: Process com.genba.dev (pid 6920) has died: vis+99 TOP 
12-06 20:37:00.961  2022  2121 I WindowManager: WIN DEATH: Window{90d554f u0 com.genba.dev/com.genba.dev.MainActivity}
12-06 20:37:00.961  2022  2121 W InputDispatcher: Attempted to unregister already unregistered input channel '90d554f com.genba.dev/com.genba.dev.MainActivity (server)'
12-06 20:37:00.962  1737  1737 I Zygote  : Process 6920 exited due to signal 9 (Killed)
12-06 20:37:00.963  2022  3891 I WindowManager: WIN DEATH: Window{ccbead6 u0 com.genba.dev/com.genba.dev.MainActivity}
12-06 20:37:00.963  2022  3891 W InputDispatcher: Attempted to unregister already unregistered input channel 'ccbead6 com.genba.dev/com.genba.dev.MainActivity (server)'
12-06 20:37:00.970  2022  2040 W InputReader: Device has associated, but no associated display id.
12-06 20:37:00.975  2022  2040 I chatty  : uid=1000(system) Binder:2022_1 identical 18 lines
12-06 20:37:00.975  2022  2040 W InputReader: Device has associated, but no associated display id.
12-06 20:37:00.991  1753  1862 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 3690496
12-06 20:37:01.005  2022  2057 I libprocessgroup: Successfully killed process cgroup uid 10133 pid 6920 in 45ms
12-06 20:37:01.005  2022  2049 W Activity

**Comment by akshgods** [comment]
I solved it by giving array to string values. ios is working number values while android not.
